<?php
$z[0]=Array("type","\r\n					<h4 class=\"page-header\" style=\"color: #c75b5f;\">\r\n                    	[field:typename /]\r\n                    	<span class=\"more-captions\" style=\"float:right;\">\r\n                    <a href=\"[field:typelink /]\" title=\"more\">more ></a>\r\n                    	</span>\r\n                     </h4>\r\n                ",42,383);
$z[1]=Array("arclist","\r\n					<li class=\"active\">\r\n						<div class=\"caption\">\r\n							<h4 class=\"title\"><a href=\"[field:arcurl /]\"title=\"\">[field:title /]</a></h4>\r\n							<span class=\"date\" style=\"float: right;\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span>\r\n						</div>\r\n					</li>\r\n            ",448,782);
$z[1][4]['titlelen']="60";
$z[1][4]['row']="8";

?>