<?php
$z[0]=Array("field","",79,108);
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n					<li class=\"active\">\r\n						<div class=\"caption\">\r\n							<h4 class=\"title\"><a href=\"[field:arcurl /]\"title=\"\">[field:title /]</a></h4>\r\n							<span class=\"date\" style=\"float: right;\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span>\r\n						</div>\r\n					</li>\r\n            ",270,604);
$z[1][4]['titlelen']="60";
$z[1][4]['row']="8";

?>