<?php
$z[0]=Array("field","",79,108);
$z[0][4]['name']="typename";
$z[1]=Array("field","",166,194);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\r\n					<li class=\"active\">\r\n						<div class=\"caption\">\r\n							<h4 class=\"title\"><a href=\"[field:typeurl /]\"title=\"\">[field:title /]1</a></h4>\r\n							<span class=\"date\" style=\"float: right;\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span>\r\n						</div>\r\n					</li>\r\n            ",295,631);
$z[2][4]['titlelen']="60";
$z[2][4]['row']="8";

?>