<?php
$z[0]=Array("field","",22,50);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",79,108);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                            {dede:list pagesize=\"10\"}\r\n                            <li>[<b>[field:typelink/]</b>]<a href=\"[field:arcurl/]\" >[field:title/]</a></li>\r\n                            {/dede:list}\r\n                            {dede:channelartlist typeid='1'}\r\n                        \r\n                        ",208,658);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>