<?php
$z[0]=Array("global","",616,643);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",683,713);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",731,756);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("field","",799,818);
$z[3][4]['name']="title";
$z[4]=Array("global","",819,845);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",1174,1201);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("global","",1399,1426);
$z[6][4]['name']="cfg_indexurl";
$z[7]=Array("global","",1493,1520);
$z[7][4]['name']="cfg_indexurl";
$z[8]=Array("global","",1596,1623);
$z[8][4]['name']="cfg_indexurl";
$z[9]=Array("include","",1753,1788);
$z[9][4]['filename']="head.htm";
$z[10]=Array("field","",1928,1957);
$z[10][4]['name']="position";
$z[11]=Array("type","[field:typename /]",2172,2213);
$z[12]=Array("arclist","\r\n                        <li><h5 class=\"title\"><a href='[field:arcurl/]'>[field:title/]</a></h5></li>\r\n            ",2362,2529);
$z[12][4]['titlelen']="60";
$z[12][4]['row']="8";
$z[13]=Array("type","\r\n                        <span class=\"more-captions\" style=\"float:right;\">\r\n            <a href=\"[field:typelink /]\" title=\"more\">more ></a>\r\n            </span>\r\n            ",2555,2754);
$z[14]=Array("field","",2935,2953);
$z[14][4]['name']="body";
$z[15]=Array("include","",2996,3033);
$z[15][4]['filename']="footer.htm";

?>