<?php
$z[0]=Array("global","",1142,1169);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",1169,1196);
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("global","",1395,1422);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",1422,1449);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",1517,1544);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",1544,1571);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("global","",1648,1675);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",1675,1702);
$z[7][4]['name']="cfg_indexurl";
$z[8]=Array("include","",1833,1868);
$z[8][4]['filename']="head.htm";
$z[9]=Array("field","",2008,2037);
$z[9][4]['name']="position";
$z[10]=Array("type","[field:typename /]",2252,2293);
$z[11]=Array("arclist","\r\n                        <li><h5 class=\"title\"><a href='[field:arcurl/]'>[field:title/]</a></h5></li>\r\n            ",2442,2609);
$z[11][4]['titlelen']="60";
$z[11][4]['row']="8";
$z[12]=Array("type","\r\n                        <span class=\"more-captions\" style=\"float:right;\">\r\n            <a href=\"[field:typelink /]\" title=\"more\">more ></a>\r\n            </span>\r\n            ",2635,2834);
$z[13]=Array("field","",3015,3033);
$z[13][4]['name']="body";
$z[14]=Array("include","",3076,3113);
$z[14][4]['filename']="footer.htm";

?>