</h3> 
       </div> 
       <div class="mod-body">
       <!--新闻列表开始--> 
        <ul class="captions captions-marker captions-nowrap">
        {dede:arclist row="12" typeid="15" titlelen="36" orderby="pubdate" orderway="desc"}
         <li>
            <div class="caption">
                <h4 class="title"><a href="[field:typeurl/]" title="[field:fulltitle/]" >[[field:typename/]]</a><a href="[field:arcurl /]">[field:title /]</a></h4>
             </div>
         </li>
                    
        {/dede:arclist}  
<!--         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0426/29051.html" title="“CMRC中国经济观察（CEO）”第49次季度报告会快报通稿">“CMRC中国经济观察（CEO）”第4...</a></h4> 
          </div> </li> 
         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0426/29056.html" title="中国经济学年会“第九届高校经济学骨干教师暑期高级研修班”邀请函">中国经济学年会“第九届高校经济学骨干教...</a></h4> 
          </div> </li> 
         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0426/29053.html" title="《观察者网》姚洋：中国经济回升 下一个7年繁荣可期">《观察者网》姚洋：中国经济回升 下一个...</a></h4> 
          </div> </li> 
         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0425/29042.html" title="《时代周报》黄益平：平稳快速的产业结构变迁是未来增长关键">《时代周报》黄益平：平稳快速的产业结构...</a></h4> 
          </div> </li> 
         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0425/29040.html" title="周其仁：一点关于想法的想法">周其仁：一点关于想法的想法</a></h4> 
          </div> </li> 
         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0424/29022.html" title="2017校运动会国发院教职工风采">2017校运动会国发院教职工风采</a></h4> 
          </div> </li> 
         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0419/28989.html" title="《南方人物周刊》 林毅夫，新结构经济学之父">《南方人物周刊》 林毅夫，新结构经济学...</a></h4> 
          </div> </li> 
         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0419/28981.html" title="【我与林毅夫】张彤：迪香式的微笑">【我与林毅夫】张彤：迪香式的微笑</a></h4> 
          </div> </li> 
         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0419/28979.html" title="【我与林毅夫】黄益平：朗润园里的孔夫子">【我与林毅夫】黄益平：朗润园里的孔夫子</a></h4> 
          </div> </li> 
         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0419/28977.html" title="中国经济学年会专题论坛暨“国际化与中国经济转型”研讨会征文通知">中国经济学年会专题论坛暨“国际化与中国...</a></h4> 
          </div> </li> 
         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0419/28975.html" title="林毅夫、塞勒斯汀.孟加：《战胜命运：跨越贫困陷阱，创造经济奇迹》">林毅夫、塞勒斯汀.孟加：《战胜命运：跨...</a></h4> 
          </div> </li> 
         <li> 
          <div class="caption"> 
           <h4 class="title"><a href="http://www.nsd.pku.edu.cn/home/xinwen/2017/0419/28974.html" title="数字金融讲坛第二讲：孙国峰、刘晓春共论“数字金融的新实践和新监管”">数字金融讲坛第二讲：孙国峰、刘晓春共论...</a></h4> 
          </div> </li> -->
        </ul>
        <!--新闻列表结束--> 
        <div class="more-captions">
         <a href="{dede:field.typeurl