<?php
$z[0]=Array("arclist","\r\n         <li>\r\n            <div class=\"caption\">\r\n                <h4 class=\"title\"><a href=\"[field:typeurl/]\" title=\"[field:fulltitle/]\" >[[field:typename/]]</a><a href=\"[field:arcurl /]\">[field:title /]</a></h4>\r\n             </div>\r\n         </li>\r\n                    \r\n        ",161,543);
$z[0][4]['row']="12";
$z[0][4]['typeid']="15";
$z[0][4]['titlelen']="36";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";

?>