<li class=""><a href="{dede:field name='typeurl'/}"><span class="arrow"></span>{dede:field name='typename'/}</a>
                    <div style="display: none;" class="header_list">
                        {dede:channel type='son' noself='yes' }
                        <a href="[field:typelink/]">[field:typename/]</a>
                        {/dede:channel}


                    </div>
                </li>