<?php
$z[0]=Array("field","",24,53);
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n         <li>\r\n            <div class=\"caption\">\r\n                <h4 class=\"title\"><a href=\"[field:typeurl/]\" title=\"[field:fulltitle/]\" >[[field:typename/]]</a><a href=\"[field:arcurl /]\">[field:title /]</a></h4>\r\n             </div>\r\n         </li>\r\n                    \r\n        ",214,596);
$z[1][4]['row']="12";
$z[1][4]['typeid']="15";
$z[1][4]['titlelen']="36";
$z[1][4]['orderby']="pubdate";
$z[1][4]['orderway']="desc";
$z[2]=Array("field","",4534,4562);
$z[2][4]['name']="typeurl";

?>