<?php
$z[0]=Array("global","",94,121);
$z[0][4]['name']="cfg_indexurl";
$z[1]=Array("global","",175,202);
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("global","",406,433);
$z[2][4]['name']="cfg_indexurl";
$z[3]=Array("channel","\r\n                <li class=\"dropdown\"><h5 class=\"title\"><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></h5></li>\r\n                ",510,726);
$z[3][4]['row']="5";
$z[3][4]['type']="top";
$z[3][4]['col']="1";

?>