<?php
$z[0]=Array("global","",184,211);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",211,238);
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("global","",443,470);
$z[2][4]['name']="cfg_indexurl";
$z[3]=Array("channel","\r\n                <li class=\"dropdown\"><h5 class=\"title\"><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></h5></li>\r\n                ",547,763);
$z[3][4]['row']="5";
$z[3][4]['type']="top";
$z[3][4]['col']="1";
$z[4]=Array("type","\r\n                <li class=\"dropdown 1070\" id=\"1070\">\r\n                    <h5 class=\"title\"><a href=\"[field:typelink/]\">[field:typename/]</a></h5>\r\n                    ",802,1006);
$z[4][4]['typeid']="1";
$z[5]=Array("channel","\r\n                                <li class=\"dropdown\"><h5 class=\"title\"><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></h5></li>\r\n                                ",1182,1419);
$z[5][4]['row']="6";
$z[5][4]['type']="son";
$z[5][4]['typeid']="1";

?>