<?php
$z[0]=Array("global","",616,643);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",683,713);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",731,756);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("field","",799,818);
$z[3][4]['name']="title";
$z[4]=Array("global","",819,845);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",1174,1201);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("global","",1399,1426);
$z[6][4]['name']="cfg_indexurl";
$z[7]=Array("global","",1493,1520);
$z[7][4]['name']="cfg_indexurl";
$z[8]=Array("include","",1650,1685);
$z[8][4]['filename']="head.htm";
$z[9]=Array("field","",1821,1850);
$z[9][4]['name']="position";
$z[10]=Array("field","",2046,2066);
$z[10][4]['name']="title";
$z[11]=Array("channel","\r\n                	<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                ",2280,2492);
$z[11][4]['type']="son";
$z[11][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[12]=Array("field","",2671,2692);
$z[12][4]['name']="content";
$z[13]=Array("include","",2748,2785);
$z[13][4]['filename']="footer.htm";

?>