<?php
$z[0]=Array("global","",1031,1058);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",1058,1085);
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("global","",1284,1311);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",1311,1338);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",1406,1433);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",1433,1460);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("include","",1591,1626);
$z[6][4]['filename']="head.htm";
$z[7]=Array("field","",1762,1791);
$z[7][4]['name']="position";
$z[8]=Array("field","",1987,2007);
$z[8][4]['name']="title";
$z[9]=Array("channel","\r\n                	<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                ",2221,2433);
$z[9][4]['type']="son";
$z[9][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[10]=Array("field","",2612,2633);
$z[10][4]['name']="content";
$z[11]=Array("include","",2689,2726);
$z[11][4]['filename']="footer.htm";

?>