<?php
$z[0]=Array("global","",616,643);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",683,713);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",731,756);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("field","",799,818);
$z[3][4]['name']="title";
$z[4]=Array("global","",819,845);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",1174,1201);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("global","",1399,1426);
$z[6][4]['name']="cfg_indexurl";
$z[7]=Array("global","",1493,1520);
$z[7][4]['name']="cfg_indexurl";
$z[8]=Array("global","",1587,1614);
$z[8][4]['name']="cfg_indexurl";
$z[9]=Array("include","",1738,1773);
$z[9][4]['filename']="head.htm";
$z[10]=Array("field","",1918,1947);
$z[10][4]['name']="position";
$z[11]=Array("field","",2162,2182);
$z[11][4]['name']="title";
$z[12]=Array("channelartlist","\r\n                        <li><h5 class=\"title\"><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></h5></li>\r\n                    ",2339,2534);
$z[13]=Array("field","",2857,2877);
$z[13][4]['name']="title";
$z[14]=Array("channelartlist","\r\n				<div class=\"smalltitle\">\r\n                {dede:type}\r\n					<h4 class=\"page-header\" style=\"color: #c75b5f;\">\r\n                    	[field:typename /]\r\n                    	<span class=\"more-captions\" style=\"float:right;\">\r\n                    <a href=\"[field:typelink /]\" title=\"more\">more ></a>\r\n                    	</span>\r\n                     </h4>\r\n                {/dede:type} \r\n				</div>\r\n				<ul class=\"captions captions-5\">\r\n            {dede:arclist titlelen='60' row='8'}\r\n					<li class=\"active\">\r\n						<div class=\"caption\">\r\n							<h4 class=\"title\"><a href=\"[field:arcurl /]\"title=\"\">[field:title /]</a></h4>\r\n							<span class=\"date\" style=\"float: right;\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span>\r\n						</div>\r\n					</li>\r\n            {/dede:arclist}\r\n				</ul>\r\n",2926,3770);
$z[15]=Array("include","",3829,3866);
$z[15][4]['filename']="footer.htm";

?>