<?php
$z[0]=Array("global","",998,1025);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",1025,1052);
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("global","",1251,1278);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",1278,1305);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",1373,1400);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",1400,1427);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("global","",1495,1522);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",1522,1549);
$z[7][4]['name']="cfg_indexurl";
$z[8]=Array("include","",1674,1709);
$z[8][4]['filename']="head.htm";
$z[9]=Array("field","",1854,1883);
$z[9][4]['name']="position";
$z[10]=Array("field","",2098,2118);
$z[10][4]['name']="title";
$z[11]=Array("channelartlist","\r\n                        <li><h5 class=\"title\"><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></h5></li>\r\n                    ",2275,2470);
$z[12]=Array("field","",2793,2813);
$z[12][4]['name']="title";
$z[13]=Array("channelartlist","\r\n				<div class=\"smalltitle\">\r\n                {dede:type}\r\n					<h4 class=\"page-header\" style=\"color: #c75b5f;\">\r\n                    	[field:typename /]\r\n                    	<span class=\"more-captions\" style=\"float:right;\">\r\n                    <a href=\"[field:typelink /]\" title=\"more\">more ></a>\r\n                    	</span>\r\n                     </h4>\r\n                {/dede:type} \r\n				</div>\r\n				<ul class=\"captions captions-5\">\r\n            {dede:arclist titlelen='60' row='8'}\r\n					<li class=\"active\">\r\n						<div class=\"caption\">\r\n							<h4 class=\"title\"><a href=\"[field:arcurl /]\"title=\"\">[field:title /]</a></h4>\r\n							<span class=\"date\" style=\"float: right;\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span>\r\n						</div>\r\n					</li>\r\n            {/dede:arclist}\r\n				</ul>\r\n",2862,3706);
$z[14]=Array("include","",3765,3802);
$z[14][4]['filename']="footer.htm";

?>