<?php
$z[0]=Array("global","",998,1025);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",1025,1052);
$z[1][4]['name']="cfg_indexurl";
$z[2]=Array("global","",1251,1278);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",1278,1305);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",1373,1400);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",1400,1427);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("global","",1495,1522);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",1522,1549);
$z[7][4]['name']="cfg_indexurl";
$z[8]=Array("include","",1649,1684);
$z[8][4]['filename']="head.htm";
$z[9]=Array("field","",1826,1855);
$z[9][4]['name']="position";
$z[10]=Array("field","",2070,2090);
$z[10][4]['name']="title";
$z[11]=Array("channel","\r\n                        <li><h5 class=\"title\"><a href='[field:typeurl/]'>[field:typename/]</a></h5></li>\r\n                    ",2247,2415);
$z[11][4]['type']="son";
$z[12]=Array("field","",2697,2717);
$z[12][4]['name']="title";
$z[13]=Array("arclist","\r\n				<li class=\"active\">\r\n					<div class=\"caption\">\r\n						<h4 class=\"title\"><a href=\"[field:arcurl /]\" title=\"\">[field:title /]</a></h4>\r\n						<span class=\"date\">[field:pubdate function=\"MyDate('y-m-d',@me)\"/]</span>\r\n					</div>\r\n				</li>\r\n            ",2784,3094);
$z[13][4]['titlelen']="60";
$z[13][4]['row']="10";
$z[14]=Array("include","",3148,3185);
$z[14][4]['filename']="footer.htm";

?>