<?php
$z[0]=Array("global","",616,643);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",683,713);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",731,756);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("field","",799,818);
$z[3][4]['name']="title";
$z[4]=Array("global","",819,845);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",1174,1201);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("global","",1399,1426);
$z[6][4]['name']="cfg_indexurl";
$z[7]=Array("global","",1493,1520);
$z[7][4]['name']="cfg_indexurl";
$z[8]=Array("global","",1587,1614);
$z[8][4]['name']="cfg_indexurl";
$z[9]=Array("include","",1713,1748);
$z[9][4]['filename']="head.htm";
$z[10]=Array("field","",1890,1919);
$z[10][4]['name']="position";
$z[11]=Array("field","",2134,2154);
$z[11][4]['name']="title";
$z[12]=Array("channel","\r\n                        <li><h5 class=\"title\"><a href='[field:typeurl/]'>[field:typename/]</a></h5></li>\r\n                    ",2311,2479);
$z[12][4]['type']="son";
$z[13]=Array("field","",2761,2781);
$z[13][4]['name']="title";
$z[14]=Array("arclist","\r\n				<li class=\"active\">\r\n					<div class=\"caption\">\r\n						<h4 class=\"title\"><a href=\"[field:arcurl /]\" title=\"\">[field:title /]</a></h4>\r\n						<span class=\"date\">[field:pubdate function=\"MyDate('y-m-d',@me)\"/]</span>\r\n					</div>\r\n				</li>\r\n            ",2848,3158);
$z[14][4]['titlelen']="60";
$z[14][4]['row']="10";
$z[15]=Array("include","",3212,3249);
$z[15][4]['filename']="footer.htm";

?>